//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int userId { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
    
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
