/****** Object:  Database [LogDates]    Script Date: 7/21/2013 10:44:55 AM ******/
IF  NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'LogDates')
CREATE DATABASE [LogDates]

USE [LogDates]

CREATE TABLE LogsDates(
  LogId int NOT NULL IDENTITY,
  LogDate datetime,
  LogText nvarchar(100),
  CONSTRAINT PK_Logs_Id PRIMARY KEY (LogId)
)
GO

ALTER DATABASE [LogDates] SET COMPATIBILITY_LEVEL = 110
GO

ALTER DATABASE [LogDates] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [LogDates] SET ANSI_NULLS ON 
GO

ALTER DATABASE [LogDates] SET ANSI_PADDING ON 
GO

ALTER DATABASE [LogDates] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [LogDates] SET ARITHABORT ON 
GO

ALTER DATABASE [LogDates] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LogDates] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LogDates] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LogDates] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LogDates] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LogDates] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [LogDates] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [LogDates] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LogDates] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [LogDates] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LogDates] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LogDates] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LogDates] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LogDates] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LogDates] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LogDates] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LogDates] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LogDates] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LogDates] SET RECOVERY FULL 
GO

ALTER DATABASE [LogDates] SET  MULTI_USER 
GO

ALTER DATABASE [LogDates] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LogDates] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LogDates] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LogDates] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LogDates] SET  READ_WRITE 
GO


